title: Example configuration
version: 1.0
prefixes:
  rdfs: http://www.w3.org/2000/01/rdf-schema#
queries:
  - title: create classes
    query: >
      prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      insert {
        graph <urn:output> {
          ?type a rdfs:Class
        }
      }
      where {
        graph <urn:input> {
          ?s a ?type
        }
      }
  - title: add label to classes
    query: >
      prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      insert {
        graph <urn:output> {
          ?type rdfs:label ?label
        }
      }
      where {
        graph <urn:output> {
          ?type a rdfs:Class.
          BIND (strafter(str(?type),"#") as ?label)
        }
      }
