title: Example configuration
version: 1.0
constructs:
  - title: create classes
    query: >
      prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      construct {
        ?type a rdfs:Class
      }
      where {
        ?s a ?type
      }
updates:
  - title: add label to classes
    query: >
      prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      insert {
        ?type rdfs:label ?label
      }
      where {
        ?type a rdfs:Class.
        BIND (strafter(str(?type),"#") as ?label)
      }
